language:
  - python

python:
  - 2.7

branches:
  only:
  - master  # only build master

# install dependencies
install:
  - pip install -r requirements.txt
    # since dateutil is packaged incorrectly
  - pip uninstall python-dateutil -y && pip install python-dateutil

# run tests
script:
  - make test

# turn off email notifications
notifications:
  email: false
